INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'Tim Robbins, Morgan Freeman', 1994, 142, 'DVD', true, false, 1, 'picture1.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('The Godfather', 'Francis Ford Coppola', 'Marlon Brando, Al Pacino', 1972, 175, 'VHS', false, true, 1, 'picture2.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('The Dark Knight', 'Christopher Nolan', 'Christian Bale, Heath Ledger', 2008, 152, 'DVD', true, false, 1, 'picture3.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('The Godfather: Part II', 'Francis Ford Coppola', 'Al Pacino, Robert De Niro', 1974, 202, 'DVD', false, true, 1, 'picture4.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'John Travolta, Uma Thurman', 1994, 154, 'CD', true, false, 1, 'picture5.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('Schindlers List', 'Steven Spielberg', 'Liam Neeson', 1993, 195, 'VHS', false, true, 1, 'picture6.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('The Lord of the Rings: The Return of the King', 'Peter Jackson', 'Elijah Wood, Viggo Mortensen', 2003, 201, 'CD', true, false, 1, 'picture7.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('The Good the Bad and the Ugly', 'Sergio Leone', 'Clint Eastwood, Eli Wallach', 1966, 161, 'VHS', false, false, 1, 'picture8.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('12 Angry Men', 'Sidney Lumet', 'Henry Fonda, Lee J. Cobb', 1957, 96, 'VHS', true, true, 1, 'picture9.jpg')
INSERT INTO movies (title, producer, mainactor, release, length, media, genuinity, rented, timesrented, picture) VALUES ('Avengers: Infinity War', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Hemsworth', 2018, 149, 'DVD', true, true, 1, 'picture10.jpg')
INSERT INTO rented (movieid, renter, date, dateover) VALUES(1, 'Gracie C. Koch','2018-01-03', '2018-03-11')
INSERT INTO rented (movieid, renter, date, dateover) VALUES(3, 'Mildred B. Rodriquez','2018-01-20', '2018-01-30')
INSERT INTO rented (movieid, renter, date, dateover) VALUES(8, 'Frank N. Kelley','2018-02-01', '2018-02-11')
INSERT INTO rented (movieid, renter, date, dateover) VALUES(5, 'Mark C. Kennedy','2018-03-01', '2018-04-11')
INSERT INTO rented (movieid, renter, date, dateover) VALUES(7, 'Janie J. Werner','2018-04-01', '2018-05-12')
INSERT INTO rented (movieid, renter, date) VALUES(6, 'Shakira G. Thompson','2018-05-01')
INSERT INTO rented (movieid, renter, date) VALUES(4, 'Frances L. Otis','2018-05-02')
INSERT INTO rented (movieid, renter, date) VALUES(2, 'Doyle E. Ludwig','2018-05-03')
INSERT INTO rented (movieid, renter, date) VALUES(9, 'Albert J. Cortez','2018-05-04')
INSERT INTO rented (movieid, renter, date) VALUES(10, 'Victoria G. Fisher','2018-05-05')